### ISSUE TITLE
Can never log in (app crashes)

### ISSUE THREAD

**Issue by stokholm** [xda/XDA-One#58]
I haven't been able to log in to my account ever, on my Nexus 5. The app crashes every time I try (message: "Unfortunately XDA One has stopped"). I've tried all of your releases.

I'm using a Nexus 5 running Android 5.0 stock at the moment. I also tried Android 4.4.4 stock, OmniROM 4.4.4 and the SlimKat ROM. Crashes there too.

I've tried changing my password to something containing just lower case characters (thinking it could be a problem with my password). But nothing I've tried has worked.

**Comment by GermainZ** [comment]
Can you post a logcat?

**Comment by stokholm** [comment]
Sure, I hope this is the part you're looking for. I don't know if I'm supposed to clear out personal information in the log as a whole, but this looked most relevant to me. Thanks.

    I/com.newrelic.agent.android(32083): Crash 74460960-411b-5c63-1f33-aff3de85dc64 successfully submitted.
    --------- beginning of crash
    E/AndroidRuntime(32083): FATAL EXCEPTION: main
    E/AndroidRuntime(32083): Process: com.xda.one, PID: 32083
    E/AndroidRuntime(32083): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.xda.one.api.model.response.ResponseUserProfileNotification.getTotal()' on a null object reference
    E/AndroidRuntime(32083): 	at com.xda.one.auth.XDAAccount.fromProfile(XDAAccount.java:66)
    E/AndroidRuntime(32083): 	at com.xda.one.api.retrofit.RetrofitUserClient$1$1.run(RetrofitUserClient.java:95)
    E/AndroidRuntime(32083): 	at com.xda.one.api.retrofit.RetrofitUserClient$1$1.run(RetrofitUserClient.java:92)
    E/AndroidRuntime(32083): 	at com.xda.one.api.retrofit.RetrofitUserClient$3.success(RetrofitUserClient.java:152)
    E/AndroidRuntime(32083): 	at com.xda.one.api.retrofit.RetrofitUserClient$3.success(RetrofitUserClient.java:144)
    E/AndroidRuntime(32083): 	at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
    E/AndroidRuntime(32083): 	at android.os.Handler.handleCallback(Handler.java:739)
    E/AndroidRuntime(32083): 	at android.os.Handler.dispatchMessage(Handler.java:95)
    E/AndroidRuntime(32083): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime(32083): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
    E/AndroidRuntime(32083): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime(32083): 	at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime(32083): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    E/AndroidRuntime(32083): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    W/ActivityManager(  825):   Force finishing activity com.xda.one/.auth.XDAAuthenticatorActivity

**Comment by stokholm** [comment]
Got a Nexus 6 now. Same issue.

**Comment by rwestergren** [comment]
@stokholm Check your XDA PMs.

**Comment by stokholm** [comment]
Hot damn. I just found the reason for the issue I think.

I couldn't reply to you on XDA because I disabled PMs. So I had to enable them. I had a crazy idea to try and see if that would let me log in and bam - it did!

So apparently you can't log in if you disable PMs under Edit Options in the control panel (Enable Private Messaging).

But thanks for taking the time to reply. Now I can start enjoying the app. :-)

**Comment by rwestergren** [comment]
Interesting! I'm pushing out a fix for the API to deal with this case. Thanks for reporting it!
