### ISSUE TITLE
Unused resources

### ISSUE THREAD

**Issue by GermainZ** [xda/XDA-One#62]
There are many unused resources. To list a few:
- context_menu.xml
- create_post_ab.xml
- create_thread_or_message_ab.xml
- thread_context_menu.xml

I can see some being potentially used, but others seem obsolete at this point since their intended functionality is already implemented differently (e.g. "subscribe"/"thanks"/"reply" buttons).

Are those okay to be removed, or are they planned for future features? (tagging @tilal6991 as he's probably the one who can answer this)

**Comment by tilal6991** [comment]
All resources there are dead I think and can be removed.

**Comment by ddrager** [comment]
Thanks @tilal6991! @GermainZ feel free to take them out.
